# Generated by Django 2.0.3 on 2020-05-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Alternative_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Alternative_food')),
            ],
        ),
        migrations.CreateModel(
            name='Main_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(max_length=64)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Main_food')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Salads_Pasta',
        ),
        migrations.DeleteModel(
            name='Subs_Dinners',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
