# Generated by Django 2.0.3 on 2020-05-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200515_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative_food',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='main_food',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
