# Generated by Django 2.0.3 on 2020-05-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200515_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative_item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='small_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
