# Generated by Django 2.0.3 on 2020-05-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200515_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='large_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
