# Generated by Django 2.0.3 on 2020-06-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200515_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('detail_json', models.TextField()),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
                'managed': True,
            },
        ),
    ]
