# Generated by Django 2.0.3 on 2020-06-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
