# Generated by Django 2.0.3 on 2020-06-08 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orders_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orders',
            name='username',
            field=models.TextField(default='pedro'),
            preserve_default=False,
        ),
    ]
